import path from 'node:path';import {fileURLToPath} from 'node:url';
import express from 'express';
import {pool,one,tx,fail} from './db.js';
import {authenticate,signIn,signOut,changeOwnPassword,resetUserPassword,onlySuper,scope,requireOffice} from './auth.js';
import {entities} from './entities.js';import {finance} from './finance.js';
import {readSupportPhone,supportPhoneKey} from './support-phone.js';
import {paymentNumbers,paymentNumbersKey,readPaymentNumbers} from './payment-numbers.js';
const app=express();app.disable('x-powered-by');app.set('trust proxy',1);app.use(express.json({limit:'1mb'}));
app.use((req,res,next)=>{if(!['GET','HEAD','OPTIONS'].includes(req.method)){const origin=req.headers.origin;const allowed=process.env.APP_ORIGIN||'http://localhost:5173';if(origin&&origin!==allowed&&origin!==`${req.protocol}://${req.get('host')}`)return res.status(403).json({error:'Origin not allowed.'});}next();});
app.get('/api/health',async(req,res)=>{await pool.query('SELECT 1');res.json({ok:true});});
app.post('/api/login',async(req,res)=>res.json(await signIn(String(req.body?.username||''),String(req.body?.password||''),res)));
app.use('/api',authenticate);
app.get('/api/me',(req,res)=>res.json(req.user));
app.put('/api/me/password',async(req,res)=>{await changeOwnPassword(req.user,String(req.body?.current_password??''),String(req.body?.new_password??''));res.json({ok:true});});
app.put('/api/users/:id/password-reset',async(req,res)=>{await resetUserPassword(req.user,req.params.id,String(req.body?.new_password??''));res.json({ok:true});});
app.post('/api/logout',async(req,res)=>{await signOut(req,res);res.json({ok:true});});
app.use('/api/entities',entities);app.use('/api',finance);
app.get('/api/backup',async(req,res)=>{onlySuper(req.user);const tables=['ib_offices','ib_users','ib_packages','ib_customers','ib_bill_batches','ib_bill_lines','ib_payments','ib_isp_payments','ib_office_expenses','ib_staff_salary','ib_line_transfer','ib_new_line','ib_settings'];
 const data=await tx(async db=>{await db.query('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY');const output={format:'IBM_PG_V1',created_at:new Date().toISOString(),tables:[]};for(const name of tables)output.tables.push({key:name,rows:(await db.query(`SELECT * FROM ${name} ORDER BY ${name==='ib_settings'?'key':'id'}`)).rows});return output;});
 res.set({'Content-Type':'application/json; charset=utf-8','Content-Disposition':`attachment; filename="internet-business-backup-${new Date().toISOString().slice(0,10)}.json"`,'Cache-Control':'no-store'});res.send(JSON.stringify(data));
});
const settingsOffice=async(u,requested)=>{const id=requireOffice(u,scope(u,requested));if(!await one(pool,'SELECT id FROM ib_offices WHERE id=$1',[id]))fail(404,'Office not found.');return id;};
app.get('/api/settings',async(req,res)=>{const officeId=await settingsOffice(req.user,req.query.office_id);const [support,numbers]=await Promise.all([readSupportPhone(pool,officeId),readPaymentNumbers(pool,officeId)]);res.json({office_id:officeId,...support,payment_numbers:numbers});});
app.put('/api/settings',async(req,res)=>{onlySuper(req.user);const officeId=await settingsOffice(req.user,req.body?.office_id),value=String(req.body?.support_phone??'').trim(),numbers=paymentNumbers(req.body?.payment_numbers);if(!value||value.length>50)fail(400,'Enter a support phone number of up to 50 characters.');if(Object.values(numbers).some(number=>number.length>25))fail(400,'Payment numbers must be 25 characters or fewer.');await tx(async db=>{await db.query('INSERT INTO ib_settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value',[supportPhoneKey(officeId),JSON.stringify(value)]);await db.query('INSERT INTO ib_settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value',[paymentNumbersKey(officeId),JSON.stringify(numbers)]);});res.json({office_id:officeId,value,inherited:false,payment_numbers:numbers});});
app.use((err,req,res,next)=>{if(res.headersSent)return next(err);if(!err.status&&err.code!=='23505')console.error(err);res.status(err.status|| (err.code==='23505'?409:500)).json({error:err.status?err.message:err.code==='23505'?'A record with this identifier already exists.':'Server error.'});});
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))app.listen(Number(process.env.PORT)||3001,()=>console.log('Internet Business Manager API listening'));
export default app;
