import path from 'node:path';import {fileURLToPath} from 'node:url';
import express from 'express';
import {pool,one,tx,fail,today} from './db.js';
import {authenticate,signIn,signOut,changeOwnPassword,resetUserPassword,parseCookie,onlySuper,scope,requireOffice,paymentCollector,paymentCollectorRoute} from './auth.js';
import {entities} from './entities.js';import {finance} from './finance.js';
import {readSupportPhone,supportPhoneKey} from './support-phone.js';
import {paymentNumbers,paymentNumbersKey,readPaymentNumbers} from './payment-numbers.js';
import {createBackupSnapshot,createOfficeBackupSnapshot} from './backup.js';
import {scheduledBackup,validBackupBearer} from './scheduled-backup.js';
import {driveFolderId,dueBackupDate,dhakaDateTime,markBackupSuccess,readBackupSchedule,saveBackupSchedule,validBackupFrequency,validBackupMonthDay,validBackupStartDate,validBackupTime,validBackupWeekday} from './backup-schedule.js';
const app=express();app.disable('x-powered-by');app.set('trust proxy',1);
app.use((req,res,next)=>{
 res.set({'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'no-referrer','Permissions-Policy':'camera=(), microphone=(), geolocation=()'});
 next();
});
app.use(express.json({limit:'1mb'}));
app.use((req,res,next)=>{if(!['GET','HEAD','OPTIONS'].includes(req.method)){const origin=req.headers.origin;const allowed=process.env.APP_ORIGIN||'http://localhost:5173';if(origin&&origin!==allowed&&origin!==`${req.protocol}://${req.get('host')}`)return res.status(403).json({error:'Origin not allowed.'});}next();});
app.get('/api/health',async(req,res)=>{await pool.query('SELECT 1');res.json({ok:true});});
app.post('/api/login',async(req,res)=>res.json(await signIn(String(req.body?.username||''),String(req.body?.password||''),res)));
const requireBackupToken=req=>{if(!validBackupBearer(req.headers.authorization,process.env.BACKUP_EXPORT_SECRET))fail(401,'Backup access denied.');};
app.get('/api/backup/scheduled',async(req,res)=>{
 requireBackupToken(req);
 if(!process.env.BACKUP_ENCRYPTION_KEY)fail(503,'Backup encryption is not configured.');
 const now=new Date(),schedule=await readBackupSchedule();
 res.set('Cache-Control','no-store');
 const backupDate=req.query.force==='1'?dhakaDateTime(now).date:dueBackupDate({now,...schedule,lastSuccess:schedule.last_success});
 if(!backupDate)return res.status(204).end();
 const {filename,bytes}=await scheduledBackup({now,backupDate});
 res.set({'Content-Type':'application/octet-stream','Content-Disposition':`attachment; filename="${filename}"`,'X-Backup-Filename':filename,'X-Backup-Date':backupDate});
 if(schedule.folder_id)res.set('X-Backup-Folder-Id',schedule.folder_id);
 res.send(bytes);
});
app.post('/api/backup/scheduled/ack',async(req,res)=>{
 requireBackupToken(req);
 const {date,file_id,filename,folder_id}=req.body||{};
 const now=new Date(),allowedDates=[dhakaDateTime(now).date,dhakaDateTime(new Date(now.getTime()-86400000)).date];
 if(!allowedDates.includes(date)||typeof file_id!=='string'||!/^[A-Za-z0-9_-]{10,200}$/.test(file_id)||driveFolderId(folder_id)!==folder_id||!folder_id||filename!==`internet-business-backup-${date}.json.enc`)fail(400,'Invalid backup confirmation.');
 await markBackupSuccess({date,file_id,filename,folder_id});
 res.json({ok:true});
});
app.use('/api',authenticate);
app.use('/api',(req,res,next)=>{
 if(!paymentCollector(req.user))return next();
 const path=req.originalUrl.split('?')[0].replace(/^\/api(?=\/|$)/,'');
 if(!paymentCollectorRoute(req.method,path))return res.status(403).json({error:'Payment Collector access only.'});
 next();
});
app.get('/api/me',(req,res)=>res.json(req.user));
app.put('/api/me/password',async(req,res)=>{await changeOwnPassword(req.user,String(req.body?.current_password??''),String(req.body?.new_password??''),parseCookie(req));res.json({ok:true});});
app.put('/api/users/:id/password-reset',async(req,res)=>{await resetUserPassword(req.user,req.params.id,String(req.body?.new_password??''));res.json({ok:true});});
app.post('/api/logout',async(req,res)=>{await signOut(req,res);res.json({ok:true});});
app.use('/api/entities',entities);app.use('/api',finance);
app.get('/api/backup',async(req,res)=>{onlySuper(req.user);
 const selected=req.query.office_id!==undefined,officeId=selected?requireOffice(req.user,req.query.office_id):0;
 const data=await tx(db=>selected?createOfficeBackupSnapshot(db,officeId):createBackupSnapshot(db));
 if(!data)fail(404,'Office not found.');
 const date=today(),filename=selected?`internet-business-office-${officeId}-backup-${date}.json`:`internet-business-all-offices-backup-${date}.json`;
 res.set({'Content-Type':'application/json; charset=utf-8','Content-Disposition':`attachment; filename="${filename}"`,'X-Backup-Filename':filename,'Cache-Control':'no-store'});res.send(JSON.stringify(data));
});
app.get('/api/backup/schedule',async(req,res)=>{onlySuper(req.user);res.json({...await readBackupSchedule(),server_ready:Boolean(process.env.BACKUP_EXPORT_SECRET?.length>=32&&process.env.BACKUP_ENCRYPTION_KEY)});});
app.put('/api/backup/schedule',async(req,res)=>{onlySuper(req.user);const {time,frequency='daily',weekday=1,month_day=1,start_date='',folder_id}=req.body||{};if(!validBackupTime(time))fail(400,'Enter a valid backup time (HH:MM).');if(!validBackupFrequency(frequency))fail(400,'Choose daily, weekly, or monthly backups.');if(!validBackupWeekday(weekday))fail(400,'Choose a weekday from Monday to Sunday.');if(!validBackupMonthDay(month_day))fail(400,'Choose a day of the month from 1 to 31.');if(!validBackupStartDate(start_date))fail(400,'Enter a valid start date (YYYY-MM-DD).');if(driveFolderId(folder_id)===null)fail(400,'Enter a Google Drive folder link or folder ID.');res.json(await saveBackupSchedule({time,frequency,weekday,month_day,start_date,folder_id}));});
const settingsOffice=async(u,requested)=>{const id=requireOffice(u,scope(u,requested));if(!await one(pool,'SELECT id FROM ib_offices WHERE id=$1',[id]))fail(404,'Office not found.');return id;};
app.get('/api/settings',async(req,res)=>{const officeId=await settingsOffice(req.user,req.query.office_id);const [support,numbers]=await Promise.all([readSupportPhone(pool,officeId),readPaymentNumbers(pool,officeId)]);res.json({office_id:officeId,...support,payment_numbers:numbers});});
app.put('/api/settings',async(req,res)=>{onlySuper(req.user);const officeId=await settingsOffice(req.user,req.body?.office_id),value=String(req.body?.support_phone??'').trim(),numbers=paymentNumbers(req.body?.payment_numbers);if(!value||value.length>50)fail(400,'Enter a support phone number of up to 50 characters.');if(Object.values(numbers).some(number=>number.length>25))fail(400,'Payment numbers must be 25 characters or fewer.');await tx(async db=>{await db.query('INSERT INTO ib_settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value',[supportPhoneKey(officeId),JSON.stringify(value)]);await db.query('INSERT INTO ib_settings(key,value) VALUES($1,$2) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value',[paymentNumbersKey(officeId),JSON.stringify(numbers)]);});res.json({office_id:officeId,value,inherited:false,payment_numbers:numbers});});
app.use((err,req,res,next)=>{if(res.headersSent)return next(err);if(!err.status&&err.code!=='23505')console.error(err);res.status(err.status|| (err.code==='23505'?409:500)).json({error:err.status?err.message:err.code==='23505'?'A record with this identifier already exists.':'Server error.'});});
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))app.listen(Number(process.env.PORT)||3001,()=>console.log('Internet Business Manager API listening'));
export default app;
